%main window
win= figure(...
    'color',[0 0.8 1],...
    'units','characters',...
    'resize','off',...
    'position',[90 10 100 30],...
    'numbertitle','off',...
    'name','Home',...
    'menubar','none',...
    'windowstyle','normal');

%frame
header = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'units','characters',...
    'position',[0 22 100 4],...
    'style','text');

%label
judulutama = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'style','text',...
    'string','WELCOME',...
    'units','characters',...
    'position',[33 22 35 4],...
    'fontsize',20);

%button
btn_interpolasi = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[39 12 22 3],...
    'string','Interpolation',...
    'fontsize',13,...
    'callback','interpolasi');

btn_smoothing = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[39 8 22 3],...
    'string','Smoothing',...
    'fontsize',13,...
    'callback','smoothing');

btn_tutup = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[39 1 22 3],...
    'string','Exit',...
    'fontsize',13,...
    'callback','quit1');
