 win=figure(...
    'color',[0 1 1],...
    'menubar','none',...
    'units','points',...
    'position',[350 140 330 250],...
    'resize','off',...
    'numbertitle','off',...
    'name','About',...
    'windowstyle','normal');

label1=uicontrol('Parent',win,...
    'Units','points',...
    'Position',[10 190 100 20],...
    'Backgroundcolor',[0 1 1],...
    'Style','text',...
    'string','Dibuat Oleh:',...
    'fontname','arial',...
    'fontsize',16,...
    'fontweight','Bold',...
    'foregroundcolor',[0 0 0]);

label2=uicontrol('Parent',win,...
    'Units','points',...
    'Position',[0 130 350 20],...
    'Backgroundcolor',[0 1 1],...
    'Style','text',...
    'string','Ziath Adam (G74150009)',...
    'fontname','arial',...
    'fontsize',16,...
    'fontweight','Bold',...
    'foregroundcolor',[0 0 0]);
label3=uicontrol('Parent',win,...
    'Units','points',...
    'Position',[0 160 350 20],...
    'Backgroundcolor',[0 1 1],...
    'Style','text',...
    'string','Muhamad Audy Valentino (G74150007)',...
    'fontname','arial',...
    'fontsize',16,...
    'fontweight','Bold',...
    'foregroundcolor',[0 0 0]);
label4=uicontrol('Parent',win,...
    'Units','points',...
    'Position',[0 100 350 20],...
    'Backgroundcolor',[0 1 1],...
    'Style','text',...
    'string','Ahmad Nur Aziz (G74150029)',...
    'fontname','arial',...
    'fontsize',16,...
    'fontweight','Bold',...
    'foregroundcolor',[0 0 0]);
label5=uicontrol('Parent',win,...
    'Units','points',...
    'Position',[110 220 100 20],...
    'Backgroundcolor',[0 1 1],...
    'Style','text',...
    'string','Tugas SSF',...
    'fontname','arial',...
    'fontsize',16,...
    'fontweight','Bold',...
    'foregroundcolor',[0 0 0]);