%clear;
%close;
%main window
win= figure(...
    'color',[0 0.8 1],...
    'units','characters',...
    'resize','off',...
    'position',[55 5 170 45],...
    'numbertitle','off',...
    'name','Interpolation',...
    'menubar','none',...
    'windowstyle','normal');

%frame
header = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'units','characters',...
    'position',[0 40 171 5],...+
    'style','text');
        
footer = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'units','characters',...
    'position',[0 0 171 5],...
    'style','text');
%label
judulutama = uicontrol('Parent',win,...
    'Backgroundcolor',[0 1 1],...
    'style','text',...
    'string','Interpolation',...
    'units','characters',...
    'position',[67 40 35 4],...
    'fontsize',20);
 
ket1 = uicontrol('Parent',win,...
    'Backgroundcolor',[0 0.8 1],...
    'style','text',...
    'string','Insert Data',...
    'units','characters',...
    'position',[1.5 37 30 2],...
    'fontsize',13.5);

ket2 = uicontrol('Parent',win,...
    'Backgroundcolor',[0 0.8 1],...
    'style','text',...
    'string','Method',...
    'units','characters',...
    'position',[-1 32 30 2],...
    'fontsize',13.5);

ket3 = uicontrol('Parent',win,...
    'Backgroundcolor',[0 0.8 1],...
    'style','text',...
    'string','Orde',...
    'units','characters',...
    'position',[-3.5 27.5 30 2],...
    'fontsize',13,...
    'visible','off');

% inputx = uicontrol('Parent',win,...
%     'Backgroundcolor',[0 0.8 1],...
%     'style','text',...
%     'string','Input',...
%     'units','characters',...
%     'position',[-3.5 21 30 2],...
%     'fontsize',13.5);
% 
% outputy = uicontrol('Parent',win,...
%     'Backgroundcolor',[0 0.8 1],...
%     'style','text',...
%     'string','Output',...
%     'units','characters',...
%     'position',[-3.5 18 30 2],...
%     'fontsize',13);


%tombol
btn_upload = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[42 35 20 2],...
    'string','Browse...',...
    'callback','LoadData');

btn_process = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[32 11 23 2.5],...
    'string','Process',...
    'fontsize',9,...
    'callback','Run');

 %     'Backgroundcolor',[1 1 1],...
%     'style','pushbutton',...
%     'units','characters',...
%     'position',[42 21 18.5 2],...
%     'string','Generate',...
%     'fontsize',9,...
%     'callback','generate');

btn_exit = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
   'position',[32 7 23 2.5],...
    'string','Close',...
    'fontsize',9,...
    'callback','quit2');

btn_reset = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 7 23 2.5],...
    'string','Reset',...
    'fontsize',9,...
    'callback','Resetgrafik');

btn_show = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 11 23 2.5],...
    'string','Show Data ',...
    'fontsize',9,...
    'callback','ShowData');

btn_info = uicontrol('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[7 1 15 2.5],...
    'string','Info',...
    'fontsize',10,...
    'callback','info');

btn_save = uicontrol ('Parent',win,...
    'Backgroundcolor',[1 1 1],...
    'style','pushbutton',...
    'units','characters',...
    'position',[25 1 15 2.5],...
    'string','Save',...
    'fontsize',10,...
    'callback','savedata');

%kolomisian
data = uicontrol('Parent',win,...
    'style','edit',...
    'units','characters',...
    'position',[7 35 34 2],...
    'enable','off');

menu_metode = uicontrol('Parent',win,...
    'style','popupmenu',...
    'units','characters',...
    'position',[7 30 34 2],...
    'fontsize',11,...
    'callback','popupevent',...
    'string','Linear|Nearest Neighbour|Polynomial|Cubic Spline|All Analytical');

orde = uicontrol('Parent',win,...
    'style','edit',...
    'units','characters',...
    'position',[7 25.5 34 2],...
    'enable','on',...
    'fontsize',11,...
    'string','1',...
    'visible','off');

% inx = uicontrol('Parent',win,...
%     'style','edit',...
%     'units','characters',...
%     'position',[18 21 23.2 2],...
%     'enable','on',...
%     'fontsize',11);
% 
% outy = uicontrol('Parent',win,...
%     'style','edit',...
%     'units','characters',...
%     'position',[18 18 23.2 2],...
%     'enable','on',...
%     'fontsize',11,...
%     'enable','off');

%grafik
grafik= axes('Parent',win,...
    'units','characters',...
    'position',[73 9 93 29]);

%--------------------------------------------------------------------
tempatfile='';
namafile='';


